import Head from 'next/head'
import { useSelector } from 'react-redux'
import { MainLayout } from '../src/PageComponents/MainLayout/MainLayout'
import { MainPage } from '../src/PageComponents/MainPage/MainPage'
import { RootState } from '../src/state'
import { NextThunkDispatch, wrapper } from '../src/state/store'
import { fetchPosts } from '../src/state/thunks'
import { getError } from '../src/utils/selectors'

export default function Home() {
  const posts = useSelector((state: RootState) => state.allPosts)
  const error = useSelector((state: RootState) => getError(state))

  return (
    <MainLayout>
      <Head>
        <title>List of all posts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {error ? <h3>{error}</h3> : <MainPage posts={posts} />}
    </MainLayout>
  )
}

export const getServerSideProps = wrapper.getServerSideProps(
  async ({ store }) => {
    const dispatch = store.dispatch as NextThunkDispatch
    await dispatch(await fetchPosts())
  }
)
